[book]
authors = ["abhilekh"]
language = "en"
multilingual = false
src = "src"
title = "Write your First Game in C++"
description = "Write your First Game in C++ - Learn and Have fun with C++ by Reading this Book From Abhilekh Gautam."

[output.html]
mathjax-support = true
